onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
# Uncomment for Pastoria development.
# overrides:
#   pastoria: link:../pastoria/packages/pastoria
#   pastoria-runtime: file:../pastoria/packages/pastoria-runtime
#   pastoria-server: link:../pastoria/packages/pastoria-server
#   pastoria-config: link:../pastoria/packages/pastoria-config
