onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild

overrides:
  '@pastoria/vite': file:./vendor/pastoria-vite.tgz
  '@pastoria/runtime': file:./vendor/pastoria-runtime.tgz
  '@pastoria/server': file:./vendor/pastoria-server.tgz
