onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild

overrides:
  pastoria: file:./vendor/pastoria.tgz
  pastoria-runtime: file:./vendor/pastoria-runtime.tgz
  pastoria-server: file:./vendor/pastoria-server.tgz
