/*
 * This file was generated by `pastoria`.
 * @generated-checksum 96fa05681908afbe324f319acb56003a574394e72ba520d7213cbdaa312aa1c1
 * Do not modify this file directly.
 */
import { EntryPoint } from "react-relay/hooks";
import { z } from "zod/v4-mini";
import { JSResource, ModuleType } from "./js_resource";

const schema = z.object({});
const entrypoint: EntryPoint<ModuleType<'route(/about)'>, {params: Record<string, any>, schema: typeof schema}> = {
    root: JSResource.fromModuleId('route(/about)'),
    getPreloadProps({params, schema}) {
      const variables = schema.parse(params);
      return {
        queries: {
        }
        ,
        entryPoints: {
        }
      }
    }
  };
type Queries = {};
type EntryPoints = {};

export {entrypoint, schema, type EntryPoints, type Queries};

