/*
 * This file was generated by `pastoria`.
 * @generated-checksum 8db334409c0a1a47f0a3cf32e3f55e709b99722c1032d081b89eb159db3b6b0f
 * Do not modify this file directly.
 */
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});
const entrypoint: EntryPoint<ModuleType<'/about'>, z.output<typeof schema>> = {
  root: JSResource.fromModuleId('/about'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};

type Queries = {};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
