/*
 * This file was generated by `pastoria`.
 * @generated-checksum e6bad17c91344087bb11b45f2c88e01d145c624a3d71beae4577f5b0feacaa06
 * Do not modify this file directly.
 */
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/about/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/about/page'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};
type Queries = {};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
