/*
 * This file was generated by `pastoria`.
 * @generated-checksum 4806829fe226dc162c14639b05ab107a4e18160adfe571a8ad4e840d6879768f
 * Do not modify this file directly.
 */
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});

const entrypoint: EntryPoint<ModuleType<'/about'>, z.output<typeof schema>> = {
  root: JSResource.fromModuleId('/about'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};

type Queries = {};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {};
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
