/*
 * This file was generated by `pastoria`.
 * @generated-checksum d8092c0161b450c1a497584cfa949d9064f11c094aa13e7f2863220c0663cfaa
 * Do not modify this file directly.
 */
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<'route(/about)'>,
  { params: Record<string, any>; schema: typeof schema }
> = {
  root: JSResource.fromModuleId('route(/about)'),
  getPreloadProps({ params, schema }) {
    const variables = schema.parse(params);
    return {
      queries: {},
      entryPoints: {},
    };
  },
};
type Queries = {};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
