/*
 * This file was generated by `pastoria`.
 * @generated-checksum 285c516d696c0d095fedc487d1a0bcb10af8423792275ac74f05aa1e0245d4e6
 * Do not modify this file directly.
 */
import { EntryPoint } from "react-relay/hooks";
import { z } from "zod/v4-mini";
import { JSResource, ModuleType } from "./js_resource";

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<"route(/about)">,
  { params: Record<string, any>; schema: typeof schema }
> = {
  root: JSResource.fromModuleId("route(/about)"),
  getPreloadProps({ params, schema }) {
    const variables = schema.parse(params);
    return {
      queries: {},
      entryPoints: {},
    };
  },
};
type Queries = {};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
