/*
 * This file was generated by `pastoria`.
 * @generated-checksum abc1eb330ab765016231afb763c050c61a51dee466dcb1bbb871d256a54a6712
 * Do not modify this file directly.
 */
import type {
  Queries,
  RuntimeProps,
} from '../../pastoria/commander/[commander]/staple_details';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import stapleDetails_CommanderStapleDetailsQueryParameters from '#genfiles/queries/stapleDetails_CommanderStapleDetailsQuery$parameters';
import type {
  stapleDetails_CommanderStapleDetailsQuery,
  stapleDetails_CommanderStapleDetailsQuery$variables,
} from '#genfiles/queries/stapleDetails_CommanderStapleDetailsQuery.graphql';

const schema = z.object({
  cardName: z.pipe(z.string(), z.transform(decodeURIComponent)),
  commander: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/commander/[commander]#staple_details'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/commander/[commander]#staple_details'),
  getPreloadProps(variables) {
    return {
      queries: {
        cardDetails: {
          parameters: stapleDetails_CommanderStapleDetailsQueryParameters,
          variables: {
            cardName: variables.cardName,
            commander: variables.commander,
          },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    cardDetails: (
      variables: stapleDetails_CommanderStapleDetailsQuery$variables,
    ) => ThinQueryParams<stapleDetails_CommanderStapleDetailsQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
