/*
 * This file was generated by `pastoria`.
 * @generated-checksum d08382c1f3cc66e93645dd3076ea5673d36e3328fcf1e51ac452a5bdc8323adb
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/commander/[commander]/entries';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import entries_CommanderEntriesQueryParameters from '#genfiles/queries/entries_CommanderEntriesQuery$parameters';
import type {
  entries_CommanderEntriesQuery,
  entries_CommanderEntriesQuery$variables,
} from '#genfiles/queries/entries_CommanderEntriesQuery.graphql';

const schema = z.object({
  commander: z.pipe(z.string(), z.transform(decodeURIComponent)),
  maxStanding: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  minEventSize: z.coerce.number<number>(),
  sortBy: z.transform(
    (s: string) =>
      s as import('../queries/entries_CommanderEntriesQuery.graphql').EntriesSortBy,
  ),
  timePeriod: z.transform(
    (s: string) =>
      s as import('../queries/entries_CommanderEntriesQuery.graphql').TimePeriod,
  ),
});

const entrypoint: EntryPoint<
  ModuleType<'/commander/[commander]#entries'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/commander/[commander]#entries'),
  getPreloadProps(variables) {
    return {
      queries: {
        entries: {
          parameters: entries_CommanderEntriesQueryParameters,
          variables: {
            commander: variables.commander,
            maxStanding: variables.maxStanding,
            minEventSize: variables.minEventSize,
            sortBy: variables.sortBy,
            timePeriod: variables.timePeriod,
          },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    entries: (
      variables: entries_CommanderEntriesQuery$variables,
    ) => ThinQueryParams<entries_CommanderEntriesQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
