/*
 * This file was generated by `pastoria`.
 * @generated-checksum 87fedf4d235bee860b8d550b728a3d0ba5133f6e6d1704b7021c1112d129f649
 * Do not modify this file directly.
 */
import type {
  EntryPoints,
  Queries,
  ExtraProps,
} from '../../pastoria/commander/[commander]/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_CommanderShellQueryParameters from '#genfiles/queries/page_CommanderShellQuery$parameters';
import page_CommanderStatsQueryParameters from '#genfiles/queries/page_CommanderStatsQuery$parameters';
import type {
  page_CommanderShellQuery,
  page_CommanderShellQuery$variables,
} from '#genfiles/queries/page_CommanderShellQuery.graphql';
import type {
  page_CommanderStatsQuery,
  page_CommanderStatsQuery$variables,
} from '#genfiles/queries/page_CommanderStatsQuery.graphql';
import {
  entrypoint as commander_$commander_entries_entrypoint,
  schema as commander_$commander_entries_schema,
} from './commander_$commander_entries.entrypoint';
import {
  entrypoint as commander_$commander_staples_entrypoint,
  schema as commander_$commander_staples_schema,
} from './commander_$commander_staples.entrypoint';
import {
  entrypoint as commander_$commander_staple_details_entrypoint,
  schema as commander_$commander_staple_details_schema,
} from './commander_$commander_staple_details.entrypoint';

const schema = z.object({
  commander: z.pipe(z.string(), z.transform(decodeURIComponent)),
  tab: z.nullish(z.string()),
  card: z.nullish(z.string()),
  sortBy: z.nullish(z.string()),
  timePeriod: z.nullish(z.string()),
  maxStanding: z.nullish(z.coerce.number()),
  minEventSize: z.nullish(z.coerce.number()),
});

const entrypoint: EntryPoint<
  ModuleType<'/commander/[commander]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/commander/[commander]'),
  getPreloadProps($variables) {
    return (({ queries, entryPoints, variables }) => {
      const tab = variables.tab ?? 'entries';
      const commander = variables.commander;
      const maxStanding = variables.maxStanding ?? undefined;
      const minEventSize = variables.minEventSize ?? 50;
      const sortBy = (variables.sortBy ?? 'TOP') as 'NEW' | 'TOP';
      const timePeriod = (variables.timePeriod ?? 'ONE_YEAR') as
        | 'ALL_TIME'
        | 'ONE_MONTH'
        | 'ONE_YEAR'
        | 'POST_BAN'
        | 'SIX_MONTHS'
        | 'THREE_MONTHS';

      return {
        queries: {
          commanderShell: queries.commanderShell({ commander }),
          commanderStats: queries.commanderStats({
            commander,
            minEventSize,
            timePeriod,
          }),
        },
        entryPoints: {
          entries:
            tab === 'entries'
              ? entryPoints.entries({
                  commander,
                  maxStanding,
                  minEventSize,
                  sortBy,
                  timePeriod,
                })
              : undefined,

          staples:
            tab === 'staples' ? entryPoints.staples({ commander }) : undefined,

          stapleDetails:
            tab === 'card' && variables.card != null
              ? entryPoints.stapleDetails({
                  commander,
                  cardName: variables.card,
                })
              : undefined,
        },
        extraProps: {
          tab,
          cardName: variables.card,
          minEventSize,
          sortBy,
          timePeriod,
          maxStanding,
        },
      } as const;
    })({
      variables: $variables,
      queries: {
        ['commanderShell']: (variables) => ({
          parameters: page_CommanderShellQueryParameters,
          variables,
        }),
        ['commanderStats']: (variables) => ({
          parameters: page_CommanderStatsQueryParameters,
          variables,
        }),
      },
      entryPoints: {
        ['entries']: (entryPointParams) => ({
          entryPoint: commander_$commander_entries_entrypoint,
          entryPointParams,
        }),
        ['staples']: (entryPointParams) => ({
          entryPoint: commander_$commander_staples_entrypoint,
          entryPointParams,
        }),
        ['stapleDetails']: (entryPointParams) => ({
          entryPoint: commander_$commander_staple_details_entrypoint,
          entryPointParams,
        }),
      },
    } satisfies PreloadPropsHelpers);
  },
};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    commanderShell: (
      variables: page_CommanderShellQuery$variables,
    ) => ThinQueryParams<page_CommanderShellQuery>;
    commanderStats: (
      variables: page_CommanderStatsQuery$variables,
    ) => ThinQueryParams<page_CommanderStatsQuery>;
  };
  entryPoints: {
    entries: (
      entryPointParams: z.output<typeof commander_$commander_entries_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/commander/[commander]#entries'>,
        ModuleParams<'/commander/[commander]#entries'>
      >
    >;
    staples: (
      entryPointParams: z.output<typeof commander_$commander_staples_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/commander/[commander]#staples'>,
        ModuleParams<'/commander/[commander]#staples'>
      >
    >;
    stapleDetails: (
      entryPointParams: z.output<
        typeof commander_$commander_staple_details_schema
      >,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/commander/[commander]#staple_details'>,
        ModuleParams<'/commander/[commander]#staple_details'>
      >
    >;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
