/*
 * This file was generated by `pastoria`.
 * @generated-checksum 3a3332b056bd279ceb938bc3fcae7c833f59991e5a48a7adbf97ede36ddcfdd9
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/commander/[commander]/staples';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import staples_CommanderStaplesQueryParameters from '#genfiles/queries/staples_CommanderStaplesQuery$parameters';
import type {
  staples_CommanderStaplesQuery,
  staples_CommanderStaplesQuery$variables,
} from '#genfiles/queries/staples_CommanderStaplesQuery.graphql';

const schema = z.object({
  commander: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/commander/[commander]#staples'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/commander/[commander]#staples'),
  getPreloadProps(variables) {
    return {
      queries: {
        staples: {
          parameters: staples_CommanderStaplesQueryParameters,
          variables: { commander: variables.commander },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    staples: (
      variables: staples_CommanderStaplesQuery$variables,
    ) => ThinQueryParams<staples_CommanderStaplesQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
