/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 */

import {PastoriaRootContext} from 'pastoria-runtime/server';

/**
 * @gqlContext
 */
export class Context extends PastoriaRootContext {}
