/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 */

import type {ComponentType} from 'react';
import type {JSResourceReference} from 'react-relay/hooks';
import type {PageProps} from './types';

type ResourceConf = typeof RESOURCE_CONF;
const RESOURCE_CONF = {
  "fs:page(/)": {
      src: "pastoria/page.tsx",
      loader: (): Promise<ComponentType<PageProps<'/'>>> => import("../../pastoria/page").then(m => m.default)
    },
  "fs:page(/)#commanders": {
      src: "pastoria/commanders.page.tsx",
      loader: (): Promise<ComponentType<PageProps<'/#commanders'>>> => import("../../pastoria/commanders.page").then(m => m.default)
    },
  "fs:page(/about)": {
      src: "pastoria/about/page.tsx",
      loader: (): Promise<ComponentType<PageProps<'/about'>>> => import("../../pastoria/about/page").then(m => m.default)
    }
} as const;

type ModuleId = keyof ResourceConf;
export type ModuleType<M extends ModuleId> = Awaited<
  ReturnType<ResourceConf[M]['loader']>
>;

export class JSResource<M extends ModuleId>
  implements JSResourceReference<ModuleType<M>>
{
  static srcOfModuleId(id: string): string | null {
    return RESOURCE_CONF[id as ModuleId].src;
  }

  private static readonly resourceCache = new Map<ModuleId, JSResource<any>>();
  static fromModuleId<M extends ModuleId>(moduleId: M) {
    if (JSResource.resourceCache.has(moduleId)) {
      return JSResource.resourceCache.get(moduleId)!;
    }

    const resource = new JSResource(moduleId);
    JSResource.resourceCache.set(moduleId, resource);
    return resource;
  }

  private constructor(private readonly moduleId: M) {}
  private modulePromiseCache: Promise<ModuleType<M>> | null = null;
  private moduleCache: ModuleType<M> | null = null;

  getModuleId(): string {
    return this.moduleId;
  }

  getModuleIfRequired(): ModuleType<M> | null {
    return this.moduleCache;
  }

  async load(): Promise<ModuleType<M>> {
    if (this.modulePromiseCache == null) {
      this.modulePromiseCache = RESOURCE_CONF[this.moduleId]
        .loader()
        .then((m) => {
          this.moduleCache = m as ModuleType<M>;
          return this.moduleCache;
        })
        .catch((err) => {
          console.error(`JSResource.load() failed for: ${this.moduleId}`, err);
          throw err;
        });
    }

    return await this.modulePromiseCache;
  }
}
