/*
 * This file was generated by `pastoria`.
 * @generated-checksum 643b3c2aa8a78bfb4ba04331c465475eaf7fb6276ab0af8654f2393cd90f8611
 * Do not modify this file directly. Instead, edit the template at js_resource.ts.
 */

import type { JSResourceReference } from 'react-relay/hooks';

type ResourceConf = typeof RESOURCE_CONF;
const RESOURCE_CONF = {
  'm#commander_stats': {
    src: 'src/commander_page.tsx',
    loader: () =>
      import('../../src/commander_page').then((m) => m.CommanderStats),
  },
  'm#commander_page': {
    src: 'src/commander_page.tsx',
    loader: () =>
      import('../../src/commander_page').then((m) => m.CommanderPage),
  },
  'm#commander_page_shell': {
    src: 'src/commander_page.tsx',
    loader: () =>
      import('../../src/commander_page').then((m) => m.CommanderPageShell),
  },
  'm#tournament_page_shell': {
    src: 'src/tournament_view.tsx',
    loader: () =>
      import('../../src/tournament_view').then((m) => m.TournamentPageShell),
  },
  'm#tournament_view': {
    src: 'src/tournament_view.tsx',
    loader: () =>
      import('../../src/tournament_view').then((m) => m.TournamentViewPage),
  },
  '#pastoria/page': {
    src: 'pastoria/page.tsx',
    loader: () => import('#pastoria//page').then((m) => m.default),
  },
  '#pastoria/about/page': {
    src: 'pastoria/about/page.tsx',
    loader: () => import('#pastoria/about/page').then((m) => m.default),
  },
  '#pastoria/staples/page': {
    src: 'pastoria/staples/page.tsx',
    loader: () => import('#pastoria/staples/page').then((m) => m.default),
  },
  '#pastoria/tournaments/page': {
    src: 'pastoria/tournaments/page.tsx',
    loader: () => import('#pastoria/tournaments/page').then((m) => m.default),
  },
} as const;

type ModuleId = keyof ResourceConf;
export type ModuleType<M extends ModuleId> = Awaited<
  ReturnType<ResourceConf[M]['loader']>
>;

export class JSResource<M extends ModuleId>
  implements JSResourceReference<ModuleType<M>>
{
  static srcOfModuleId(id: string): string | null {
    return RESOURCE_CONF[id as ModuleId].src;
  }

  private static readonly resourceCache = new Map<ModuleId, JSResource<any>>();
  static fromModuleId<M extends ModuleId>(moduleId: M) {
    if (JSResource.resourceCache.has(moduleId)) {
      return JSResource.resourceCache.get(moduleId)!;
    }

    const resource = new JSResource(moduleId);
    JSResource.resourceCache.set(moduleId, resource);
    return resource;
  }

  private constructor(private readonly moduleId: M) {}
  private modulePromiseCache: Promise<ModuleType<M>> | null = null;
  private moduleCache: ModuleType<M> | null = null;

  getModuleId(): string {
    return this.moduleId;
  }

  getModuleIfRequired(): ModuleType<M> | null {
    return this.moduleCache;
  }

  async load(): Promise<ModuleType<M>> {
    if (this.modulePromiseCache == null) {
      this.modulePromiseCache = RESOURCE_CONF[this.moduleId]
        .loader()
        .then((m) => {
          this.moduleCache = m as ModuleType<M>;
          return this.moduleCache;
        });
    }

    return await this.modulePromiseCache;
  }
}
