/*
 * This file was generated by `pastoria`.
 * @generated-checksum 442a112ef6994debb0fe1782c17f765c0a48c882ab1841f6a8b250ba40f383f9
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/leaderboard/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_LeaderboardQueryParameters from '#genfiles/queries/page_LeaderboardQuery$parameters';
import type {
  page_LeaderboardQuery,
  page_LeaderboardQuery$variables,
} from '#genfiles/queries/page_LeaderboardQuery.graphql';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/leaderboard'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/leaderboard'),
  getPreloadProps(variables) {
    return {
      queries: {
        leaderboardRef: {
          parameters: page_LeaderboardQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    leaderboardRef: (
      variables: page_LeaderboardQuery$variables,
    ) => ThinQueryParams<page_LeaderboardQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
