/*
 * This file was generated by `pastoria`.
 * @generated-checksum 624d808f5892898c689869be9cd87134aab99eac2c37e890f8efa63cc8e9c721
 * Do not modify this file directly.
 */
import type { Queries, ExtraProps } from '../../pastoria/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HomePagePromoQueryParameters from '#genfiles/queries/page_HomePagePromoQuery$parameters';
import page_CommandersQueryParameters from '#genfiles/queries/page_CommandersQuery$parameters';
import type {
  page_HomePagePromoQuery,
  page_HomePagePromoQuery$variables,
} from '#genfiles/queries/page_HomePagePromoQuery.graphql';
import type {
  page_CommandersQuery,
  page_CommandersQuery$variables,
} from '#genfiles/queries/page_CommandersQuery.graphql';

const schema = z.object({
  colorId: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  minEntries: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  minSize: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  sortBy: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_CommandersQuery.graphql').CommandersSortBy,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  timePeriod: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_CommandersQuery.graphql').TimePeriod,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});

const entrypoint: EntryPoint<ModuleType<'/'>, z.output<typeof schema>> = {
  root: JSResource.fromModuleId('/'),
  getPreloadProps($variables) {
    return (({ queries, variables }) => {
      return {
        queries: {
          promoQueryRef: queries.promoQueryRef({}),
          commandersQueryRef: queries.commandersQueryRef(variables),
        },
        entryPoints: {},
        extraProps: {
          sortBy: variables.sortBy ?? 'POPULARITY',
          timePeriod: variables.timePeriod ?? 'SIX_MONTHS',
          minEntries: variables.minEntries ?? 20,
          minTournamentSize: variables.minSize ?? 50,
          colorId: variables.colorId ?? '',
        },
      };
    })({
      variables: $variables,
      queries: {
        ['promoQueryRef']: (variables) => ({
          parameters: page_HomePagePromoQueryParameters,
          variables,
        }),
        ['commandersQueryRef']: (variables) => ({
          parameters: page_CommandersQueryParameters,
          variables,
        }),
      },
      entryPoints: {},
    } satisfies PreloadPropsHelpers);
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    promoQueryRef: (
      variables: page_HomePagePromoQuery$variables,
    ) => ThinQueryParams<page_HomePagePromoQuery>;
    commandersQueryRef: (
      variables: page_CommandersQuery$variables,
    ) => ThinQueryParams<page_CommandersQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
