/*
 * This file was generated by `pastoria`.
 * @generated-checksum 23f7982e1ba648278cf3806468296ab5352fdd1080cfbff4aaea6287286b69a0
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HomePagePromoQueryParameters from '#genfiles/queries/page_HomePagePromoQuery$parameters';
import page_CommandersQueryParameters from '#genfiles/queries/page_CommandersQuery$parameters';

const schema = z.object({
  colorId: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  minEntries: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  minSize: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  sortBy: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_CommandersQuery.graphql').CommandersSortBy,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  timePeriod: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_CommandersQuery.graphql').TimePeriod,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        promoQueryRef: {
          parameters: page_HomePagePromoQueryParameters,
          variables: {},
        },
        commandersQueryRef: {
          parameters: page_CommandersQueryParameters,
          variables: {
            colorId: variables.colorId,
            minEntries: variables.minEntries,
            minSize: variables.minSize,
            sortBy: variables.sortBy,
            timePeriod: variables.timePeriod,
          },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
