/*
 * This file was generated by `pastoria`.
 * @generated-checksum 139eded67c480928c51839b8d9e3af589f872b4d7614fa63046ad0c44ebb31de
 * Do not modify this file directly.
 */
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/privacy/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/privacy/page'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};
type Queries = {};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
