/*
 * This file was generated by `pastoria`.
 * @generated-checksum af8cd40623a1a5aac8b652820495beb8935cfcbf4264f71578fd9a0b71829a6f
 * Do not modify this file directly.
 */
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/privacy'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/privacy'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};

type Queries = {};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
