/*
 * This file was generated by `pastoria`.
 * @generated-checksum ec7883fa083099286bf0299b7f2a706ebfcaf9ef2cd31effeba82be9e07ee7c0
 * Do not modify this file directly.
 */
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/privacy'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/privacy'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};

type Queries = {};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {};
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
