/*
 * This file was generated by `pastoria`.
 * @generated-checksum 37c67e8f1bb534570411f6599da3717e4845e8e8ba6de1b1a8ea8b54d3f3ad19
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/profile/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page__ClaimProfileQueryParameters from '#genfiles/queries/page__ClaimProfileQuery$parameters';
import type {
  page__ClaimProfileQuery,
  page__ClaimProfileQuery$variables,
} from '#genfiles/queries/page__ClaimProfileQuery.graphql';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/profile'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/profile'),
  getPreloadProps(variables) {
    return {
      queries: {
        claimQuery: {
          parameters: page__ClaimProfileQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    claimQuery: (
      variables: page__ClaimProfileQuery$variables,
    ) => ThinQueryParams<page__ClaimProfileQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
