/*
 * This file was generated by `pastoria`.
 * @generated-checksum 4641005ec2ff442765b2cc12fc888ba2f022c29dbae9f33b60c933091303722d
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/profile/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page__ClaimProfileQueryParameters from '#genfiles/queries/page__ClaimProfileQuery$parameters';

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/profile/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/profile/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        claimQuery: {
          parameters: page__ClaimProfileQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
