/*
 * This file was generated by `pastoria`.
 * @generated-checksum bc710ce1fb698e234fc47f9091ec11909a3899be774399ed8b8379d7f2135222
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/reports/monthly_seat_winrates/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_MonthlySeatWinRatesQueryParameters from '#genfiles/queries/page_MonthlySeatWinRatesQuery$parameters';
import type {
  page_MonthlySeatWinRatesQuery,
  page_MonthlySeatWinRatesQuery$variables,
} from '#genfiles/queries/page_MonthlySeatWinRatesQuery.graphql';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/reports/monthly_seat_winrates'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/reports/monthly_seat_winrates'),
  getPreloadProps(variables) {
    return {
      queries: {
        monthlySeatWinRatesRef: {
          parameters: page_MonthlySeatWinRatesQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    monthlySeatWinRatesRef: (
      variables: page_MonthlySeatWinRatesQuery$variables,
    ) => ThinQueryParams<page_MonthlySeatWinRatesQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
