/*
 * This file was generated by `pastoria`.
 * @generated-checksum cedab05e3fd36bcee29bacd62f74cc9b444b5fc15b0c9e7ce3088e79c95866e3
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/reports/country_winrates/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_CountryWinRatesQueryParameters from '#genfiles/queries/page_CountryWinRatesQuery$parameters';
import type {
  page_CountryWinRatesQuery,
  page_CountryWinRatesQuery$variables,
} from '#genfiles/queries/page_CountryWinRatesQuery.graphql';

const schema = z.object({
  minTournaments: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});

const entrypoint: EntryPoint<
  ModuleType<'/reports/country_winrates'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/reports/country_winrates'),
  getPreloadProps(variables) {
    return {
      queries: {
        countryWinRatesQueryRef: {
          parameters: page_CountryWinRatesQueryParameters,
          variables: { minTournaments: variables.minTournaments },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    countryWinRatesQueryRef: (
      variables: page_CountryWinRatesQuery$variables,
    ) => ThinQueryParams<page_CountryWinRatesQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
