/*
 * This file was generated by `pastoria`.
 * @generated-checksum f02f4bb3a4a7263876badbffe683bbcc31f5c9697c65b38221dd31092567f3ba
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/reports/country_winrates/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_CountryWinRatesQueryParameters from '#genfiles/queries/page_CountryWinRatesQuery$parameters';

const schema = z.object({
  minTournaments: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/reports/country_winrates/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/reports/country_winrates/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        countryWinRatesQueryRef: {
          parameters: page_CountryWinRatesQueryParameters,
          variables: { minTournaments: variables.minTournaments },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
