/*
 * This file was generated by `pastoria`.
 * @generated-checksum 36b6d798ffd0b446b5fc1fed91e1761780a9103c82a0df9cec5dd1af96676d34
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/reports/monthly_seat_winrates/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_MonthlySeatWinRatesQueryParameters from '#genfiles/queries/page_MonthlySeatWinRatesQuery$parameters';
import type {
  page_MonthlySeatWinRatesQuery,
  page_MonthlySeatWinRatesQuery$variables,
} from '#genfiles/queries/page_MonthlySeatWinRatesQuery.graphql';

const schema = z.object({
  commanderName: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  phase: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_MonthlySeatWinRatesQuery.graphql').TournamentPhase,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});

const entrypoint: EntryPoint<
  ModuleType<'/reports/monthly_seat_winrates'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/reports/monthly_seat_winrates'),
  getPreloadProps(variables) {
    return {
      queries: {
        monthlySeatWinRatesRef: {
          parameters: page_MonthlySeatWinRatesQueryParameters,
          variables: {
            commanderName: variables.commanderName,
            phase: variables.phase,
          },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    monthlySeatWinRatesRef: (
      variables: page_MonthlySeatWinRatesQuery$variables,
    ) => ThinQueryParams<page_MonthlySeatWinRatesQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
