/*
 * This file was generated by `pastoria`.
 * @generated-checksum 1abb9e5b87c0a0bdc6351e6ef1aed1fc3e6d21c61f2a9d6ebf728dff665ff25b
 * Do not modify this file directly. Instead, edit the template at server.ts.
 */

import express from 'express';
import { default as e0 } from '../../pastoria/ads.txt/route';

export const router = express.Router();
router.use('/ads.txt', e0);
