/*
 * This file was generated by `pastoria`.
 * @generated-checksum 9ea24b4fcf25c59079c1500e4b78ccd65321b819b6fbd0d073b28c7273bfe542
 * Do not modify this file directly. Instead, edit the template at server.ts.
 */

import express from 'express';

export const router = express.Router();
