/*
 * This file was generated by `pastoria`.
 * @generated-checksum eb3d80e4e34881e2d240b011f895bc60dbde60af6ce0c1ac21ea76cdf095a0e1
 * Do not modify this file directly. Instead, edit the template at server.ts.
 */

import express from "express";

export const router = express.Router();
