/*
 * This file was generated by `pastoria`.
 * @generated-checksum 7573b5062914997d192cd54ae14fcba79ed9b49fb17666b69f04f5a005b7093b
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/staples/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_StaplesQueryParameters from '#genfiles/queries/page_StaplesQuery$parameters';

const schema = z.object({
  colorId: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  type: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/staples/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/staples/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        staplesQueryRef: {
          parameters: page_StaplesQueryParameters,
          variables: { colorId: variables.colorId, type: variables.type },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
