/*
 * This file was generated by `pastoria`.
 * @generated-checksum 65cf4796d99af8d2ce7e29256f4f840e790d6a43909ecb761d9d382563366e66
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/staples/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_StaplesQueryParameters from '#genfiles/queries/page_StaplesQuery$parameters';
import type {
  page_StaplesQuery,
  page_StaplesQuery$variables,
} from '#genfiles/queries/page_StaplesQuery.graphql';

const schema = z.object({
  colorId: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  type: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});

const entrypoint: EntryPoint<
  ModuleType<'/staples'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/staples'),
  getPreloadProps(variables) {
    return {
      queries: {
        staplesQueryRef: {
          parameters: page_StaplesQueryParameters,
          variables: { colorId: variables.colorId, type: variables.type },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    staplesQueryRef: (
      variables: page_StaplesQuery$variables,
    ) => ThinQueryParams<page_StaplesQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
