/*
 * This file was generated by `pastoria`.
 * @generated-checksum 49e104e09a22156e686e13d5501793ca962051bfef514cac797a43590380d53e
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/tournaments/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_TournamentsQueryParameters from '#genfiles/queries/page_TournamentsQuery$parameters';

const schema = z.object({
  minSize: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  sortBy: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_TournamentsQuery.graphql').TournamentSortBy,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  timePeriod: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_TournamentsQuery.graphql').TimePeriod,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/tournaments/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/tournaments/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        tournamentQueryRef: {
          parameters: page_TournamentsQueryParameters,
          variables: {
            minSize: variables.minSize,
            sortBy: variables.sortBy,
            timePeriod: variables.timePeriod,
          },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
