/*
 * This file was generated by `pastoria`.
 * @generated-checksum d4b759b70348bfad5d427a9ebfe3a8cba03a300236b1025cb8400d3820e8ebd4
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/tournaments/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_TournamentsQueryParameters from '#genfiles/queries/page_TournamentsQuery$parameters';
import type {
  page_TournamentsQuery,
  page_TournamentsQuery$variables,
} from '#genfiles/queries/page_TournamentsQuery.graphql';

const schema = z.object({
  minSize: z.pipe(
    z.nullish(z.coerce.number<number>()),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  sortBy: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_TournamentsQuery.graphql').TournamentSortBy,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
  timePeriod: z.pipe(
    z.nullish(
      z.transform(
        (s: string) =>
          s as import('../queries/page_TournamentsQuery.graphql').TimePeriod,
      ),
    ),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});

const entrypoint: EntryPoint<
  ModuleType<'/tournaments'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/tournaments'),
  getPreloadProps(variables) {
    return {
      queries: {
        tournamentQueryRef: {
          parameters: page_TournamentsQueryParameters,
          variables: {
            minSize: variables.minSize,
            sortBy: variables.sortBy,
            timePeriod: variables.timePeriod,
          },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    tournamentQueryRef: (
      variables: page_TournamentsQuery$variables,
    ) => ThinQueryParams<page_TournamentsQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
