/*
 * This file was generated by `pastoria`.
 * @generated-checksum 69d30c4c49545837299762c6d38cd1cb80ad9fcd333b53e1c3e062c380b3a471
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/tournament/[tid]/breakdown';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import breakdown_TournamentBreakdownQueryParameters from '#genfiles/queries/breakdown_TournamentBreakdownQuery$parameters';
import type {
  breakdown_TournamentBreakdownQuery,
  breakdown_TournamentBreakdownQuery$variables,
} from '#genfiles/queries/breakdown_TournamentBreakdownQuery.graphql';

const schema = z.object({
  tid: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/tournament/[tid]#breakdown'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/tournament/[tid]#breakdown'),
  getPreloadProps(variables) {
    return {
      queries: {
        breakdown: {
          parameters: breakdown_TournamentBreakdownQueryParameters,
          variables: { tid: variables.tid },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    breakdown: (
      variables: breakdown_TournamentBreakdownQuery$variables,
    ) => ThinQueryParams<breakdown_TournamentBreakdownQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
