/*
 * This file was generated by `pastoria`.
 * @generated-checksum 315e47e75bdbf0b7805dad520a84ab70ac2b42520da18125e2341a60d5a7c58d
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/tournament/[tid]/standings';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import standings_TournamentStandingsQueryParameters from '#genfiles/queries/standings_TournamentStandingsQuery$parameters';
import type {
  standings_TournamentStandingsQuery,
  standings_TournamentStandingsQuery$variables,
} from '#genfiles/queries/standings_TournamentStandingsQuery.graphql';

const schema = z.object({
  tid: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/tournament/[tid]#standings'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/tournament/[tid]#standings'),
  getPreloadProps(variables) {
    return {
      queries: {
        standings: {
          parameters: standings_TournamentStandingsQueryParameters,
          variables: { tid: variables.tid },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    standings: (
      variables: standings_TournamentStandingsQuery$variables,
    ) => ThinQueryParams<standings_TournamentStandingsQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
