/*
 * This file was generated by `pastoria`.
 * @generated-checksum 965197e088f426f080fa149754c4a7f31029a3f82d1ea1908bf0887ef47b0c48
 * Do not modify this file directly.
 */
import type {
  EntryPoints,
  Queries,
  ExtraProps,
} from '../../pastoria/tournament/[tid]/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_TournamentPageShellQueryParameters from '#genfiles/queries/page_TournamentPageShellQuery$parameters';
import type {
  page_TournamentPageShellQuery,
  page_TournamentPageShellQuery$variables,
} from '#genfiles/queries/page_TournamentPageShellQuery.graphql';
import {
  entrypoint as tournament_$tid_standings_entrypoint,
  schema as tournament_$tid_standings_schema,
} from './tournament_$tid_standings.entrypoint';
import {
  entrypoint as tournament_$tid_breakdown_entrypoint,
  schema as tournament_$tid_breakdown_schema,
} from './tournament_$tid_breakdown.entrypoint';
import {
  entrypoint as tournament_$tid_commander_breakdown_entrypoint,
  schema as tournament_$tid_commander_breakdown_schema,
} from './tournament_$tid_commander_breakdown.entrypoint';

const schema = z.object({
  tid: z.string(),
  commander: z.nullish(z.string()),
  tab: z.nullish(z.string()),
  seatWinRates: z.nullish(z.string()),
});

const entrypoint: EntryPoint<
  ModuleType<'/tournament/[tid]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/tournament/[tid]'),
  getPreloadProps($variables) {
    return (({ queries, variables, entryPoints }) => {
      const tab = variables.tab ?? 'entries';
      return {
        queries: {
          tournamentRef: queries.tournamentRef(variables),
        },
        extraProps: {
          commanderName: variables.commander,
          tab,
          showSeatWinRates: variables.seatWinRates === 'true',
        },
        entryPoints: {
          tournamentEntries:
            tab === 'entries'
              ? entryPoints.tournamentEntries({ tid: variables.tid })
              : undefined,

          tournamentBreakdown:
            tab === 'breakdown'
              ? entryPoints.tournamentBreakdown({ tid: variables.tid })
              : undefined,

          commanderBreakdown:
            tab === 'commander' && variables.commander != null
              ? entryPoints.commanderBreakdown({
                  tid: variables.tid,
                  commander: variables.commander,
                })
              : undefined,
        },
      };
    })({
      variables: $variables,
      queries: {
        ['tournamentRef']: (variables) => ({
          parameters: page_TournamentPageShellQueryParameters,
          variables,
        }),
      },
      entryPoints: {
        ['tournamentEntries']: (entryPointParams) => ({
          entryPoint: tournament_$tid_standings_entrypoint,
          entryPointParams,
        }),
        ['tournamentBreakdown']: (entryPointParams) => ({
          entryPoint: tournament_$tid_breakdown_entrypoint,
          entryPointParams,
        }),
        ['commanderBreakdown']: (entryPointParams) => ({
          entryPoint: tournament_$tid_commander_breakdown_entrypoint,
          entryPointParams,
        }),
      },
    } satisfies PreloadPropsHelpers);
  },
};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    tournamentRef: (
      variables: page_TournamentPageShellQuery$variables,
    ) => ThinQueryParams<page_TournamentPageShellQuery>;
  };
  entryPoints: {
    tournamentEntries: (
      entryPointParams: z.output<typeof tournament_$tid_standings_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/tournament/[tid]#standings'>,
        ModuleParams<'/tournament/[tid]#standings'>
      >
    >;
    tournamentBreakdown: (
      entryPointParams: z.output<typeof tournament_$tid_breakdown_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/tournament/[tid]#breakdown'>,
        ModuleParams<'/tournament/[tid]#breakdown'>
      >
    >;
    commanderBreakdown: (
      entryPointParams: z.output<
        typeof tournament_$tid_commander_breakdown_schema
      >,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/tournament/[tid]#commander_breakdown'>,
        ModuleParams<'/tournament/[tid]#commander_breakdown'>
      >
    >;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
