/*
 * This file was generated by `pastoria`.
 * @generated-checksum fcf440d222fa6d297edc58c2c68bb51d3e4213758a6b2f8b6bdb010bfb2cbdf7
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/tournament/[tid]/commander_breakdown';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import commanderBreakdown_BreakdownQueryParameters from '#genfiles/queries/commanderBreakdown_BreakdownQuery$parameters';
import type {
  commanderBreakdown_BreakdownQuery,
  commanderBreakdown_BreakdownQuery$variables,
} from '#genfiles/queries/commanderBreakdown_BreakdownQuery.graphql';

const schema = z.object({
  commander: z.pipe(z.string(), z.transform(decodeURIComponent)),
  tid: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/tournament/[tid]#commander_breakdown'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/tournament/[tid]#commander_breakdown'),
  getPreloadProps(variables) {
    return {
      queries: {
        breakdown: {
          parameters: commanderBreakdown_BreakdownQueryParameters,
          variables: { commander: variables.commander, tid: variables.tid },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = {};

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    breakdown: (
      variables: commanderBreakdown_BreakdownQuery$variables,
    ) => ThinQueryParams<commanderBreakdown_BreakdownQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
