/*
 * This file was generated by `pastoria`.
 * @generated-checksum 32b40d9fc3c233a20d32876b83330beb229d0425e85399c604b0d41e9fcf35ff
 * Do not modify this file directly.
 */
import type { EntryPointProps, PreloadProps } from 'react-relay/hooks';
import type { z } from 'zod/v4-mini';
import type {
  Queries as page_EP_Queries,
  EntryPoints as page_EP_EntryPoints,
  schema as page_EP_schema,
  PreloadPropsHelpers as page_EP_PreloadPropsHelpers,
} from './page.entrypoint';
import type {
  Queries as about_page_EP_Queries,
  EntryPoints as about_page_EP_EntryPoints,
  schema as about_page_EP_schema,
  PreloadPropsHelpers as about_page_EP_PreloadPropsHelpers,
} from './about_page.entrypoint';
import type {
  Queries as privacy_page_EP_Queries,
  EntryPoints as privacy_page_EP_EntryPoints,
  schema as privacy_page_EP_schema,
  PreloadPropsHelpers as privacy_page_EP_PreloadPropsHelpers,
} from './privacy_page.entrypoint';
import type {
  Queries as profile_page_EP_Queries,
  EntryPoints as profile_page_EP_EntryPoints,
  schema as profile_page_EP_schema,
  PreloadPropsHelpers as profile_page_EP_PreloadPropsHelpers,
} from './profile_page.entrypoint';
import type {
  Queries as staples_page_EP_Queries,
  EntryPoints as staples_page_EP_EntryPoints,
  schema as staples_page_EP_schema,
  PreloadPropsHelpers as staples_page_EP_PreloadPropsHelpers,
} from './staples_page.entrypoint';
import type {
  Queries as tournaments_page_EP_Queries,
  EntryPoints as tournaments_page_EP_EntryPoints,
  schema as tournaments_page_EP_schema,
  PreloadPropsHelpers as tournaments_page_EP_PreloadPropsHelpers,
} from './tournaments_page.entrypoint';
import type {
  Queries as reports_country_winrates_page_EP_Queries,
  EntryPoints as reports_country_winrates_page_EP_EntryPoints,
  schema as reports_country_winrates_page_EP_schema,
  PreloadPropsHelpers as reports_country_winrates_page_EP_PreloadPropsHelpers,
} from './reports_country_winrates_page.entrypoint';

declare global {
  type PastoriaRouteName =
    | '/.'
    | '/about'
    | '/privacy'
    | '/profile'
    | '/staples'
    | '/tournaments'
    | '/reports/country_winrates';

  type PastoriaPageQueries = {
    ['/.']: page_EP_Queries;
    ['/about']: about_page_EP_Queries;
    ['/privacy']: privacy_page_EP_Queries;
    ['/profile']: profile_page_EP_Queries;
    ['/staples']: staples_page_EP_Queries;
    ['/tournaments']: tournaments_page_EP_Queries;
    ['/reports/country_winrates']: reports_country_winrates_page_EP_Queries;
  };

  type PastoriaPageEntryPoints = {
    ['/.']: page_EP_EntryPoints;
    ['/about']: about_page_EP_EntryPoints;
    ['/privacy']: privacy_page_EP_EntryPoints;
    ['/profile']: profile_page_EP_EntryPoints;
    ['/staples']: staples_page_EP_EntryPoints;
    ['/tournaments']: tournaments_page_EP_EntryPoints;
    ['/reports/country_winrates']: reports_country_winrates_page_EP_EntryPoints;
  };

  type PastoriaPageProps<T extends PastoriaRouteName> = EntryPointProps<
    PastoriaPageQueries[T],
    PastoriaPageEntryPoints[T],
    {},
    {}
  >;

  type PastoriaPreloadPropsParams = {
    ['/.']: z.output<typeof page_EP_schema>;
    ['/about']: z.output<typeof about_page_EP_schema>;
    ['/privacy']: z.output<typeof privacy_page_EP_schema>;
    ['/profile']: z.output<typeof profile_page_EP_schema>;
    ['/staples']: z.output<typeof staples_page_EP_schema>;
    ['/tournaments']: z.output<typeof tournaments_page_EP_schema>;
    ['/reports/country_winrates']: z.output<
      typeof reports_country_winrates_page_EP_schema
    >;
  };

  type PastoriaPreloadPropsHelpers = {
    ['/.']: page_EP_PreloadPropsHelpers;
    ['/about']: about_page_EP_PreloadPropsHelpers;
    ['/privacy']: privacy_page_EP_PreloadPropsHelpers;
    ['/profile']: profile_page_EP_PreloadPropsHelpers;
    ['/staples']: staples_page_EP_PreloadPropsHelpers;
    ['/tournaments']: tournaments_page_EP_PreloadPropsHelpers;
    ['/reports/country_winrates']: reports_country_winrates_page_EP_PreloadPropsHelpers;
  };

  type GetPreloadProps<R extends PastoriaRouteName> = (
    params: PastoriaPreloadPropsHelpers[R],
  ) => PreloadProps<
    PastoriaPreloadPropsParams[R],
    PastoriaPageQueries[R],
    PastoriaPageEntryPoints[R],
    {}
  >;
}
