/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 *
 * Type definitions for filesystem-based routing.
 */

import type {EntryPoint, EntryPointComponent, EntryPointProps} from 'react-relay/hooks';

import type {commanders_CommandersQuery} from '#genfiles/queries/commanders_CommandersQuery.graphql';
import type {content_StaplesQuery} from '#genfiles/queries/content_StaplesQuery.graphql';
import type {tournaments_TournamentsQuery} from '#genfiles/queries/tournaments_TournamentsQuery.graphql';
import type {page_HomePagePromoQuery} from '#genfiles/queries/page_HomePagePromoQuery.graphql';
import type {page_TournamentPageQuery} from '#genfiles/queries/page_TournamentPageQuery.graphql';

import type {page_HomePagePromoQuery$variables} from '#genfiles/queries/page_HomePagePromoQuery.graphql';
import type {commanders_CommandersQuery$variables} from '#genfiles/queries/commanders_CommandersQuery.graphql';
import type {content_StaplesQuery$variables} from '#genfiles/queries/content_StaplesQuery.graphql';
import type {tournaments_TournamentsQuery$variables} from '#genfiles/queries/tournaments_TournamentsQuery.graphql';
import type {page_TournamentPageQuery$variables} from '#genfiles/queries/page_TournamentPageQuery.graphql';

// Route type aliases - nested entry points (leaf nodes)
type RouteRoot_commanders = { queries: { commandersQueryRef: commanders_CommandersQuery }; entryPoints: {} };
type RouteStaples_content = { queries: { staplesQueryRef: content_StaplesQuery }; entryPoints: {} };
type RouteTournaments_tournaments = { queries: { tournamentQueryRef: tournaments_TournamentsQuery }; entryPoints: {} };

// Route type aliases - main pages
type RouteRoot = { queries: { promoQueryRef: page_HomePagePromoQuery }; entryPoints: { commanders: EntryPoint<EntryPointComponent<RouteRoot_commanders['queries'], RouteRoot_commanders['entryPoints'], {}, {}>, {}> } };
type RouteAbout = { queries: {}; entryPoints: {} };
type RouteStaples = { queries: {}; entryPoints: { content: EntryPoint<EntryPointComponent<RouteStaples_content['queries'], RouteStaples_content['entryPoints'], {}, {}>, {}> } };
type RouteTournaments = { queries: {}; entryPoints: { tournaments: EntryPoint<EntryPointComponent<RouteTournaments_tournaments['queries'], RouteTournaments_tournaments['entryPoints'], {}, {}>, {}> } };
type RouteTournament$tid = { queries: { tournamentQueryRef: page_TournamentPageQuery }; entryPoints: {} };

/**
 * Map of route paths to their query types.
 * Nested entry points use the format: '/route#entryPointName'
 */
export interface PageQueryMap {
  '/': RouteRoot;
  '/#commanders': RouteRoot_commanders;
  '/about': RouteAbout;
  '/staples': RouteStaples;
  '/staples#content': RouteStaples_content;
  '/tournaments': RouteTournaments;
  '/tournaments#tournaments': RouteTournaments_tournaments;
  '/tournament/[tid]': RouteTournament$tid;
}

// Query helper type aliases for each route
type QueryHelpers_RouteRoot = { promoQueryRef: (variables: page_HomePagePromoQuery$variables) => { parameters: unknown; variables: page_HomePagePromoQuery$variables } };
type QueryHelpers_RouteAbout = {};
type QueryHelpers_RouteStaples = {};
type QueryHelpers_RouteTournaments = {};
type QueryHelpers_RouteTournament$tid = { tournamentQueryRef: (variables: page_TournamentPageQuery$variables) => { parameters: unknown; variables: page_TournamentPageQuery$variables } };

// Entry point helper type aliases for each route
type EntryPointHelpers_RouteRoot = { commanders: (variables: commanders_CommandersQuery$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteRoot_commanders['queries'], RouteRoot_commanders['entryPoints'], {}, {}>, {}> } };
type EntryPointHelpers_RouteAbout = {};
type EntryPointHelpers_RouteStaples = { content: (variables: content_StaplesQuery$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteStaples_content['queries'], RouteStaples_content['entryPoints'], {}, {}>, {}> } };
type EntryPointHelpers_RouteTournaments = { tournaments: (variables: tournaments_TournamentsQuery$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteTournaments_tournaments['queries'], RouteTournaments_tournaments['entryPoints'], {}, {}>, {}> } };
type EntryPointHelpers_RouteTournament$tid = {};

/**
 * Query helper functions for a route.
 * Each helper takes typed variables and returns {parameters, variables} for Relay.
 */
export interface QueryHelpersMap {
  '/': QueryHelpers_RouteRoot;
  '/about': QueryHelpers_RouteAbout;
  '/staples': QueryHelpers_RouteStaples;
  '/tournaments': QueryHelpers_RouteTournaments;
  '/tournament/[tid]': QueryHelpers_RouteTournament$tid;
}

export type QueryHelpersForRoute<R extends string> = R extends keyof QueryHelpersMap
  ? QueryHelpersMap[R]
  : {};

/**
 * Entry point helper functions for a route.
 * Each helper takes typed variables and returns the nested entry point configuration.
 */
export interface EntryPointHelpersMap {
  '/': EntryPointHelpers_RouteRoot;
  '/about': EntryPointHelpers_RouteAbout;
  '/staples': EntryPointHelpers_RouteStaples;
  '/tournaments': EntryPointHelpers_RouteTournaments;
  '/tournament/[tid]': EntryPointHelpers_RouteTournament$tid;
}

export type EntryPointHelpersForRoute<R extends string> = R extends keyof EntryPointHelpersMap
  ? EntryPointHelpersMap[R]
  : {};

/**
 * Props type for a page component at the given route.
 * Uses EntryPointProps to transform raw query types to PreloadedQuery<...>.
 *
 * @example
 * ```typescript
 * // Main page
 * export default function BlogPosts({ queries }: PageProps<'/posts'>) {
 *   const data = usePreloadedQuery(query, queries.posts);
 * }
 *
 * // Nested entry point
 * export default function Sidebar({ queries }: PageProps<'/posts#sidebar'>) {
 *   const data = usePreloadedQuery(query, queries.sidebarData);
 * }
 * ```
 */
export type PageProps<R extends keyof PageQueryMap> = EntryPointProps<
  PageQueryMap[R]['queries'],
  PageQueryMap[R]['entryPoints'],
  {},
  {}
>;

/**
 * Return type for getPreloadProps in entrypoint.ts files.
 * This type matches the structure expected by Relay's loadEntryPoint.
 *
 * @example
 * ```typescript
 * export default function getPreloadProps({
 *   params,
 *   queries,
 *   entryPoints,
 * }: EntryPointParams<'/posts'>): PreloadPropsForRoute<'/posts'> {
 *   return {
 *     queries: {
 *       postsQuery: queries.postsQuery(params),
 *     },
 *     entryPoints: {
 *       sidebar: entryPoints.sidebar({}),
 *     },
 *   };
 * }
 * ```
 */
export type PreloadPropsForRoute<R extends keyof PageQueryMap> = {
  queries: {
    [K in keyof PageQueryMap[R]['queries']]: {
      parameters: unknown;
      variables: unknown;
    };
  };
  entryPoints: PageQueryMap[R]['entryPoints'] extends Record<string, never>
    ? undefined
    : {
        [K in keyof PageQueryMap[R]['entryPoints']]: {
          entryPointParams: unknown;
          entryPoint: unknown;
        };
      };
};
