/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */
import { createCommanderCardsLoader as createCommanderCardsLoader, commanderStatsLoader as commanderStatsLoader, createCommanderLoader as createCommanderLoader, Commander as queryCommanderResolver, Commander as queryCommandersResolver } from "./../../src/lib/server/schema/commander";
import { id as commanderIdResolver, id as entryIdResolver, id as playerIdResolver, id as tournamentIdResolver, id as cardIdResolver } from "./../../src/lib/server/schema/connection";
import { createPlayerLoader as createPlayerLoader, Player as queryCheatersResolver, Player as queryPlayerResolver } from "./../../src/lib/server/schema/player";
import { createTournamentLoader as createTournamentLoader, Tournament as queryTournamentResolver } from "./../../src/lib/server/schema/tournament";
import { Card as queryCardResolver, Card as queryStaplesResolver } from "./../../src/lib/server/schema/card";
import { searchResults as querySearchResultsResolver } from "./../../src/lib/server/schema/search";
import { GraphQLSchema, GraphQLObjectType, GraphQLString, GraphQLInt, GraphQLList, GraphQLNonNull, GraphQLID, GraphQLInputObjectType, GraphQLEnumType, GraphQLBoolean, GraphQLFloat, GraphQLInterfaceType } from "graphql";
export function getSchema(): GraphQLSchema {
    const TimePeriodType: GraphQLEnumType = new GraphQLEnumType({
        name: "TimePeriod",
        values: {
            ALL_TIME: {
                value: "ALL_TIME"
            },
            ONE_MONTH: {
                value: "ONE_MONTH"
            },
            ONE_YEAR: {
                value: "ONE_YEAR"
            },
            POST_BAN: {
                value: "POST_BAN"
            },
            SIX_MONTHS: {
                value: "SIX_MONTHS"
            },
            THREE_MONTHS: {
                value: "THREE_MONTHS"
            }
        }
    });
    const EntriesFilterType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "EntriesFilter",
        fields() {
            return {
                maxStanding: {
                    name: "maxStanding",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                minEventSize: {
                    name: "minEventSize",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                timePeriod: {
                    name: "timePeriod",
                    type: new GraphQLNonNull(TimePeriodType)
                }
            };
        }
    });
    const EntriesSortByType: GraphQLEnumType = new GraphQLEnumType({
        name: "EntriesSortBy",
        values: {
            NEW: {
                value: "NEW"
            },
            TOP: {
                value: "TOP"
            }
        }
    });
    const FirstPartyPromoType: GraphQLObjectType = new GraphQLObjectType({
        name: "FirstPartyPromo",
        fields() {
            return {
                backgroundImageUrl: {
                    name: "backgroundImageUrl",
                    type: GraphQLString
                },
                buttonText: {
                    name: "buttonText",
                    type: GraphQLString
                },
                description: {
                    name: "description",
                    type: new GraphQLList(new GraphQLNonNull(GraphQLString))
                },
                href: {
                    name: "href",
                    type: GraphQLString
                },
                imageUrl: {
                    name: "imageUrl",
                    type: GraphQLString
                },
                title: {
                    name: "title",
                    type: GraphQLString
                }
            };
        }
    });
    const CardEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "CardEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: GraphQLString
                },
                node: {
                    name: "node",
                    type: CardType
                }
            };
        }
    });
    const PageInfoType: GraphQLObjectType = new GraphQLObjectType({
        name: "PageInfo",
        fields() {
            return {
                endCursor: {
                    name: "endCursor",
                    type: GraphQLString
                },
                hasNextPage: {
                    name: "hasNextPage",
                    type: GraphQLBoolean
                },
                hasPreviousPage: {
                    name: "hasPreviousPage",
                    type: GraphQLBoolean
                },
                startCursor: {
                    name: "startCursor",
                    type: GraphQLString
                }
            };
        }
    });
    const CardConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "CardConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(CardEdgeType))
                },
                pageInfo: {
                    name: "pageInfo",
                    type: PageInfoType
                }
            };
        }
    });
    const CommanderCalculatedStatsType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommanderCalculatedStats",
        fields() {
            return {
                conversionRate: {
                    name: "conversionRate",
                    type: GraphQLFloat
                },
                count: {
                    name: "count",
                    type: GraphQLInt
                },
                metaShare: {
                    name: "metaShare",
                    type: GraphQLFloat
                },
                topCuts: {
                    name: "topCuts",
                    type: GraphQLInt
                }
            };
        }
    });
    const CommanderStatsFiltersType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "CommanderStatsFilters",
        fields() {
            return {
                colorId: {
                    name: "colorId",
                    type: new GraphQLNonNull(GraphQLString)
                },
                maxDate: {
                    name: "maxDate",
                    type: new GraphQLNonNull(GraphQLString)
                },
                maxSize: {
                    name: "maxSize",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                minDate: {
                    name: "minDate",
                    type: new GraphQLNonNull(GraphQLString)
                },
                minSize: {
                    name: "minSize",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                timePeriod: {
                    name: "timePeriod",
                    type: new GraphQLNonNull(TimePeriodType)
                }
            };
        }
    });
    const NodeType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "Node",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const CommanderType: GraphQLObjectType = new GraphQLObjectType({
        name: "Commander",
        fields() {
            return {
                breakdownUrl: {
                    name: "breakdownUrl",
                    type: GraphQLString
                },
                cards: {
                    name: "cards",
                    type: new GraphQLList(new GraphQLNonNull(CardType)),
                    resolve(source, _args, context) {
                        return source.cards(createCommanderCardsLoader(context));
                    }
                },
                colorId: {
                    name: "colorId",
                    type: GraphQLString
                },
                entries: {
                    name: "entries",
                    type: EntryConnectionType,
                    args: {
                        after: {
                            type: GraphQLID
                        },
                        filters: {
                            type: EntriesFilterType
                        },
                        first: {
                            type: new GraphQLNonNull(GraphQLInt),
                            defaultValue: 20
                        },
                        sortBy: {
                            type: new GraphQLNonNull(EntriesSortByType),
                            defaultValue: "TOP"
                        }
                    },
                    resolve(source, args) {
                        return source.entries(args.first, args.after, args.filters, args.sortBy);
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return commanderIdResolver(source);
                    }
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                promo: {
                    name: "promo",
                    type: FirstPartyPromoType
                },
                staples: {
                    name: "staples",
                    type: CardConnectionType,
                    args: {
                        after: {
                            type: GraphQLID
                        },
                        first: {
                            type: new GraphQLNonNull(GraphQLInt),
                            defaultValue: 20
                        }
                    },
                    resolve(source, args) {
                        return source.staples(args.first, args.after);
                    }
                },
                stats: {
                    name: "stats",
                    type: CommanderCalculatedStatsType,
                    args: {
                        filters: {
                            type: new GraphQLNonNull(CommanderStatsFiltersType)
                        }
                    },
                    resolve(source, args, context) {
                        return source.stats(args.filters, commanderStatsLoader(context));
                    }
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const PlayerType: GraphQLObjectType = new GraphQLObjectType({
        name: "Player",
        fields() {
            return {
                conversionRate: {
                    name: "conversionRate",
                    type: GraphQLFloat
                },
                draws: {
                    name: "draws",
                    type: GraphQLInt
                },
                entries: {
                    name: "entries",
                    type: new GraphQLList(new GraphQLNonNull(EntryType))
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return playerIdResolver(source);
                    }
                },
                isKnownCheater: {
                    name: "isKnownCheater",
                    type: GraphQLBoolean
                },
                losses: {
                    name: "losses",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                topCuts: {
                    name: "topCuts",
                    type: GraphQLInt
                },
                topdeckProfile: {
                    name: "topdeckProfile",
                    type: GraphQLString
                },
                winRate: {
                    name: "winRate",
                    type: GraphQLFloat
                },
                wins: {
                    name: "wins",
                    type: GraphQLInt
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const TournamentBreakdownGroupType: GraphQLObjectType = new GraphQLObjectType({
        name: "TournamentBreakdownGroup",
        fields() {
            return {
                commander: {
                    name: "commander",
                    type: CommanderType,
                    resolve(source, _args, context) {
                        return source.commander(createCommanderLoader(context));
                    }
                },
                commanderId: {
                    name: "commanderId",
                    type: GraphQLInt
                },
                conversionRate: {
                    name: "conversionRate",
                    type: GraphQLFloat
                },
                entries: {
                    name: "entries",
                    type: GraphQLInt
                },
                topCuts: {
                    name: "topCuts",
                    type: GraphQLInt
                }
            };
        }
    });
    const TournamentType: GraphQLObjectType = new GraphQLObjectType({
        name: "Tournament",
        fields() {
            return {
                TID: {
                    name: "TID",
                    type: GraphQLString
                },
                bracketUrl: {
                    name: "bracketUrl",
                    type: GraphQLString
                },
                breakdown: {
                    name: "breakdown",
                    type: new GraphQLList(new GraphQLNonNull(TournamentBreakdownGroupType))
                },
                entries: {
                    name: "entries",
                    type: new GraphQLList(new GraphQLNonNull(EntryType)),
                    args: {
                        commander: {
                            type: GraphQLString
                        },
                        maxStanding: {
                            type: GraphQLInt
                        }
                    },
                    resolve(source, args) {
                        return source.entries(args.commander, args.maxStanding);
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return tournamentIdResolver(source);
                    }
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                promo: {
                    name: "promo",
                    type: FirstPartyPromoType
                },
                size: {
                    name: "size",
                    type: GraphQLInt
                },
                swissRounds: {
                    name: "swissRounds",
                    type: GraphQLInt
                },
                topCut: {
                    name: "topCut",
                    type: GraphQLInt
                },
                tournamentDate: {
                    name: "tournamentDate",
                    type: GraphQLString
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const EntryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Entry",
        fields() {
            return {
                commander: {
                    name: "commander",
                    type: CommanderType,
                    resolve(source, _args, context) {
                        return source.commander(createCommanderLoader(context));
                    }
                },
                decklist: {
                    name: "decklist",
                    type: GraphQLString
                },
                draws: {
                    name: "draws",
                    type: GraphQLInt
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return entryIdResolver(source);
                    }
                },
                losses: {
                    name: "losses",
                    type: GraphQLInt
                },
                lossesBracket: {
                    name: "lossesBracket",
                    type: GraphQLInt
                },
                lossesSwiss: {
                    name: "lossesSwiss",
                    type: GraphQLInt
                },
                maindeck: {
                    name: "maindeck",
                    type: new GraphQLList(new GraphQLNonNull(CardType))
                },
                player: {
                    name: "player",
                    type: PlayerType,
                    resolve(source, _args, context) {
                        return source.player(createPlayerLoader(context));
                    }
                },
                standing: {
                    name: "standing",
                    type: GraphQLInt
                },
                tournament: {
                    name: "tournament",
                    type: TournamentType,
                    resolve(source, _args, context) {
                        return source.tournament(createTournamentLoader(context));
                    }
                },
                winRate: {
                    name: "winRate",
                    type: GraphQLFloat
                },
                wins: {
                    name: "wins",
                    type: GraphQLInt
                },
                winsBracket: {
                    name: "winsBracket",
                    type: GraphQLInt
                },
                winsSwiss: {
                    name: "winsSwiss",
                    type: GraphQLInt
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const EntryEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "EntryEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: GraphQLString
                },
                node: {
                    name: "node",
                    type: EntryType
                }
            };
        }
    });
    const EntryConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "EntryConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(EntryEdgeType))
                },
                pageInfo: {
                    name: "pageInfo",
                    type: PageInfoType
                }
            };
        }
    });
    const CardEntriesFiltersType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "CardEntriesFilters",
        fields() {
            return {
                colorId: {
                    name: "colorId",
                    type: GraphQLString
                },
                commanderName: {
                    name: "commanderName",
                    type: GraphQLString
                },
                tournamentTID: {
                    name: "tournamentTID",
                    type: GraphQLString
                }
            };
        }
    });
    const CardType: GraphQLObjectType = new GraphQLObjectType({
        name: "Card",
        fields() {
            return {
                cardPreviewImageUrl: {
                    description: "Image of the full front card face.",
                    name: "cardPreviewImageUrl",
                    type: GraphQLString
                },
                cmc: {
                    name: "cmc",
                    type: GraphQLInt
                },
                colorId: {
                    name: "colorId",
                    type: GraphQLString
                },
                entries: {
                    name: "entries",
                    type: EntryConnectionType,
                    args: {
                        after: {
                            type: GraphQLID
                        },
                        filters: {
                            type: CardEntriesFiltersType
                        },
                        first: {
                            type: new GraphQLNonNull(GraphQLInt),
                            defaultValue: 20
                        }
                    },
                    resolve(source, args) {
                        return source.entries(args.first, args.after, args.filters);
                    }
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return cardIdResolver(source);
                    }
                },
                imageUrls: {
                    description: "URL's of art crops for each card face.",
                    name: "imageUrls",
                    type: new GraphQLList(new GraphQLNonNull(GraphQLString))
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                oracleId: {
                    name: "oracleId",
                    type: GraphQLString
                },
                scryfallUrl: {
                    description: "Link to the card on Scryfall.",
                    name: "scryfallUrl",
                    type: GraphQLString
                },
                type: {
                    name: "type",
                    type: GraphQLString
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const CommanderEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommanderEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: GraphQLString
                },
                node: {
                    name: "node",
                    type: CommanderType
                }
            };
        }
    });
    const CommanderConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommanderConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(new GraphQLNonNull(CommanderEdgeType))
                },
                pageInfo: {
                    name: "pageInfo",
                    type: PageInfoType
                }
            };
        }
    });
    const CommandersSortByType: GraphQLEnumType = new GraphQLEnumType({
        name: "CommandersSortBy",
        values: {
            CONVERSION: {
                value: "CONVERSION"
            },
            POPULARITY: {
                value: "POPULARITY"
            },
            TOP_CUTS: {
                value: "TOP_CUTS"
            }
        }
    });
    const SearchResultType: GraphQLObjectType = new GraphQLObjectType({
        name: "SearchResult",
        fields() {
            return {
                name: {
                    name: "name",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: GraphQLString
                }
            };
        }
    });
    const SearchResultTypeType: GraphQLEnumType = new GraphQLEnumType({
        name: "SearchResultType",
        values: {
            COMMANDER: {
                value: "COMMANDER"
            },
            TOURNAMENT: {
                value: "TOURNAMENT"
            }
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                card: {
                    name: "card",
                    type: CardType,
                    args: {
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return queryCardResolver.card(args.name);
                    }
                },
                cheaters: {
                    name: "cheaters",
                    type: new GraphQLList(new GraphQLNonNull(PlayerType)),
                    resolve() {
                        return queryCheatersResolver.cheaters();
                    }
                },
                commander: {
                    name: "commander",
                    type: CommanderType,
                    args: {
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return queryCommanderResolver.commander(args.name);
                    }
                },
                commanders: {
                    name: "commanders",
                    type: CommanderConnectionType,
                    args: {
                        after: {
                            type: GraphQLID
                        },
                        colorId: {
                            type: GraphQLString
                        },
                        first: {
                            type: new GraphQLNonNull(GraphQLInt),
                            defaultValue: 20
                        },
                        minEntries: {
                            type: GraphQLInt
                        },
                        minTournamentSize: {
                            type: GraphQLInt
                        },
                        sortBy: {
                            type: new GraphQLNonNull(CommandersSortByType),
                            defaultValue: "CONVERSION"
                        },
                        timePeriod: {
                            type: new GraphQLNonNull(TimePeriodType),
                            defaultValue: "ONE_MONTH"
                        }
                    },
                    resolve(_source, args) {
                        return queryCommandersResolver.commanders(args.first, args.after, args.minEntries, args.minTournamentSize, args.timePeriod, args.sortBy, args.colorId);
                    }
                },
                player: {
                    name: "player",
                    type: PlayerType,
                    args: {
                        profile: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return queryPlayerResolver.player(args.profile);
                    }
                },
                searchResults: {
                    name: "searchResults",
                    type: new GraphQLList(new GraphQLNonNull(SearchResultType)),
                    args: {
                        types: {
                            type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(SearchResultTypeType)))
                        }
                    },
                    resolve(_source, args) {
                        return querySearchResultsResolver(args.types);
                    }
                },
                staples: {
                    name: "staples",
                    type: new GraphQLList(new GraphQLNonNull(CardType)),
                    resolve() {
                        return queryStaplesResolver.staples();
                    }
                },
                tournament: {
                    name: "tournament",
                    type: TournamentType,
                    args: {
                        TID: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return queryTournamentResolver.tournament(args.TID);
                    }
                }
            };
        }
    });
    const EntrySortByType: GraphQLEnumType = new GraphQLEnumType({
        name: "EntrySortBy",
        values: {
            DATE: {
                value: "DATE"
            },
            DRAWS: {
                value: "DRAWS"
            },
            LOSSES: {
                value: "LOSSES"
            },
            STANDING: {
                value: "STANDING"
            },
            WINRATE: {
                value: "WINRATE"
            },
            WINS: {
                value: "WINS"
            }
        }
    });
    const SortDirectionType: GraphQLEnumType = new GraphQLEnumType({
        name: "SortDirection",
        values: {
            ASC: {
                value: "ASC"
            },
            DESC: {
                value: "DESC"
            }
        }
    });
    const TournamentSortByType: GraphQLEnumType = new GraphQLEnumType({
        name: "TournamentSortBy",
        values: {
            DATE: {
                value: "DATE"
            },
            PLAYERS: {
                value: "PLAYERS"
            }
        }
    });
    const EntryFiltersType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "EntryFilters",
        fields() {
            return {
                maxDate: {
                    name: "maxDate",
                    type: GraphQLString
                },
                maxDraws: {
                    name: "maxDraws",
                    type: GraphQLInt
                },
                maxLosses: {
                    name: "maxLosses",
                    type: GraphQLInt
                },
                maxSize: {
                    name: "maxSize",
                    type: GraphQLInt
                },
                maxStanding: {
                    name: "maxStanding",
                    type: GraphQLInt
                },
                maxWins: {
                    name: "maxWins",
                    type: GraphQLInt
                },
                minDate: {
                    name: "minDate",
                    type: GraphQLString
                },
                minDraws: {
                    name: "minDraws",
                    type: GraphQLInt
                },
                minLosses: {
                    name: "minLosses",
                    type: GraphQLInt
                },
                minSize: {
                    name: "minSize",
                    type: GraphQLInt
                },
                minStanding: {
                    name: "minStanding",
                    type: GraphQLInt
                },
                minWins: {
                    name: "minWins",
                    type: GraphQLInt
                }
            };
        }
    });
    const TournamentFiltersType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "TournamentFilters",
        fields() {
            return {
                maxDate: {
                    name: "maxDate",
                    type: GraphQLString
                },
                maxSize: {
                    name: "maxSize",
                    type: GraphQLInt
                },
                minDate: {
                    name: "minDate",
                    type: GraphQLString
                },
                minSize: {
                    name: "minSize",
                    type: GraphQLInt
                },
                timePeriod: {
                    name: "timePeriod",
                    type: TimePeriodType
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [CommandersSortByType, EntriesSortByType, EntrySortByType, SearchResultTypeType, SortDirectionType, TimePeriodType, TournamentSortByType, NodeType, CardEntriesFiltersType, CommanderStatsFiltersType, EntriesFilterType, EntryFiltersType, TournamentFiltersType, CardType, CardConnectionType, CardEdgeType, CommanderType, CommanderCalculatedStatsType, CommanderConnectionType, CommanderEdgeType, EntryType, EntryConnectionType, EntryEdgeType, FirstPartyPromoType, PageInfoType, PlayerType, QueryType, SearchResultType, TournamentType, TournamentBreakdownGroupType]
    });
}
